[package]
name = "gold-node"
version.workspace = true
edition.workspace = true

[[bin]]
name = "gold-node"
path = "src/main.rs"

[dependencies]
gold-core = { path = "../core" }
gold-crypto = { path = "../crypto" }
gold-state = { path = "../state" }
gold-mempool = { path = "../mempool" }
gold-executor = { path = "../executor" }
gold-consensus = { path = "../consensus" }
gold-storage = { path = "../storage" }
gold-api = { path = "../api" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
